name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ninjascl/gha-notes@main
        with:
          note: "testing note. should be added to the latest commit."
